# Generated by Django 4.2.11 on 2024-09-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='today',
            name='task_status',
        ),
    ]
